# https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml

version: '3'

services:

  hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test:
    build: .
    depends_on:
      - chrome
    extra_hosts:
     - "host.docker.internal:host-gateway"
